package api

import (
	"io"
	"text/template"
)

var installShTmpl = template.Must(template.New("install.sh").Parse(`#!/bin/sh
# Sigil client installer — generated by sigils
# Usage: {{ .Usage }}
set -e

SERVER_URL="{{ .ServerURL }}"
TOKEN=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --token) TOKEN="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -z "$TOKEN" ]; then
  echo "Usage: sh install.sh --token <TOKEN>" >&2
  exit 1
fi

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
  x86_64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
esac

DEST=/usr/local/bin/sigilc
echo "Downloading sigilc for $OS/$ARCH..."
curl -fsSL "$SERVER_URL/download/sigilc?os=$OS&arch=$ARCH" -o "$DEST"
chmod +x "$DEST"

echo "Enrolling..."
"$DEST" enroll --token "$TOKEN"

echo "Installing system service..."
"$DEST" service install

echo "Starting service..."
"$DEST" service start

echo "Done."
`))

// installPs1Tmpl is the Windows installer. It holds only ASCII, which reads
// the same in every encoding Windows PowerShell 5.1 may assume for it. It runs
// as a script block in the operator's own session, which exit would close, so
// every failure throws instead: a cmdlet's through $ErrorActionPreference, and
// sigilc's through its exit code, which PowerShell does not check by itself.
var installPs1Tmpl = template.Must(template.New("install.ps1").Parse(`# Sigil client installer for Windows, generated by sigils.
# Run it in an elevated Windows PowerShell 5.1 or PowerShell 7:
#   {{ .Usage }}
param([Parameter(Mandatory = $true)][string]$Token)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $Principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw 'Run this installer in an elevated PowerShell (Run as administrator).'
}

$ServerURL = '{{ .ServerURL }}'

$MachineArch = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }
$Arch = switch ($MachineArch.ToUpperInvariant()) {
    'AMD64' { 'amd64' }
    'ARM64' { 'arm64' }
    'X86'   { '386' }
    default { throw "Unsupported Windows architecture: $MachineArch" }
}

$Dest = 'C:\Program Files\Sigil\sigilc.exe'
New-Item -ItemType Directory -Force -Path (Split-Path $Dest) | Out-Null

Write-Host "Downloading sigilc for windows/$Arch..."
Invoke-WebRequest -UseBasicParsing -Uri "$ServerURL/download/sigilc?os=windows&arch=$Arch" -OutFile $Dest

Write-Host 'Enrolling...'
& $Dest enroll --token $Token
if ($LASTEXITCODE -ne 0) { throw "sigilc enroll failed with exit code $LASTEXITCODE" }

Write-Host 'Installing system service...'
& $Dest service install
if ($LASTEXITCODE -ne 0) { throw "sigilc service install failed with exit code $LASTEXITCODE" }

Write-Host 'Starting service...'
& $Dest service start
if ($LASTEXITCODE -ne 0) { throw "sigilc service start failed with exit code $LASTEXITCODE" }

Write-Host 'Done.'
`))

// usageToken stands for the token in the usage comments of the scripts.
const usageToken = "<TOKEN>"

type installData struct {
	ServerURL string
	// Usage is the command of InstallCommands that runs the script.
	Usage string
}

func renderInstallSh(w io.Writer, serverURL string) {
	sh, _ := InstallCommands(serverURL, usageToken)
	_ = installShTmpl.Execute(w, installData{ServerURL: serverURL, Usage: sh})
}

// renderInstallPs1 writes the Windows installer, which is the same for every
// request: the token reaches it as the -Token argument, never through the
// server.
func renderInstallPs1(w io.Writer, serverURL string) {
	_, ps1 := InstallCommands(serverURL, usageToken)
	_ = installPs1Tmpl.Execute(w, installData{ServerURL: serverURL, Usage: ps1})
}
