package api

import (
	"io"
	"text/template"
)

// installShTmpl is the Linux and macOS installer. It runs from a pipe, as
// sh's standard input, so it reads the token it asks for from the terminal.
// sigilc gets the token through its environment, which unlike its command
// line other users cannot read. On a host where the sigilc service is
// installed, it stops the service before it replaces sigilc, and installs the
// service anew after enrolling, since kardianos does not install over one.
var installShTmpl = template.Must(template.New("install.sh").Parse(`#!/bin/sh
# Sigil client installer, generated by sigils. Run it as root:
#   {{ .WithToken }}
# installs sigilc and enrolls it with the token or, where sigilc is
# installed, installs it again and enrolls it anew. For the name of an
# enrolled client, create the token with
#   sigils token create --name <name> --replace
# Without --token, the installer asks for the token on the terminal, which
# keeps it off the command line: prefer this on a host that others use.
#   {{ .AskToken }}
# With --upgrade, it replaces sigilc on a host where it is installed and
# restarts its service, which keeps its enrollment.
#   {{ .Upgrade }}
set -e

SERVER_URL="{{ .ServerURL }}"
DEST=/usr/local/bin/sigilc
TOKEN=""
UPGRADE=""

usage() {
  echo "usage: sh install.sh [--token <TOKEN>]  install sigilc, or install it again with a new token" >&2
  echo "       sh install.sh --upgrade           replace sigilc and restart its service" >&2
  echo "Without --token, the token is read from the terminal. For the name of an enrolled" >&2
  echo "client, create the token with: sigils token create --name <name> --replace" >&2
  exit 2
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --token)
      if [ "$#" -lt 2 ] || [ -z "$2" ]; then usage; fi
      TOKEN="$2"
      shift 2
      ;;
    --upgrade) UPGRADE=1; shift ;;
    *) usage ;;
  esac
done
if [ -n "$UPGRADE" ] && [ -n "$TOKEN" ]; then usage; fi

# A signal ends the installer through exit, which runs the EXIT traps below:
# they restore the terminal and remove the download.
trap 'exit 1' HUP INT TERM

if [ -z "$UPGRADE" ] && [ -z "$TOKEN" ]; then
  if ! (: </dev/tty) 2>/dev/null; then
    echo "No terminal to read the token from: pass --token <TOKEN>." >&2
    exit 2
  fi
  echo "For the name of an enrolled client, create the token with --replace." >/dev/tty
  printf 'Enrollment token: ' >/dev/tty
  trap 'stty echo </dev/tty' EXIT
  stty -echo </dev/tty
  read -r TOKEN </dev/tty || :
  stty echo </dev/tty
  trap - EXIT
  echo >/dev/tty
  if [ -z "$TOKEN" ]; then usage; fi
fi

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
case "$ARCH" in
  x86_64) ARCH=amd64 ;;
  aarch64|arm64) ARCH=arm64 ;;
  i386|i686) ARCH=386 ;;
esac

# One rename puts the download in the place of the installed sigilc: a
# download that fails leaves that as it was, and a sigilc that runs keeps the
# file it started from.
TMP=$(mktemp "$DEST.XXXXXX")
trap 'rm -f "$TMP"' EXIT
echo "Downloading sigilc for $OS/$ARCH..."
curl -fsSL "$SERVER_URL/download/sigilc?os=$OS&arch=$ARCH" -o "$TMP"
chmod 0755 "$TMP"
# A sigilc that does not run fails here, before anything changes, and not
# below, where it would pass for a host without the service.
"$TMP" version

# The service of an earlier install is stopped before sigilc is replaced,
# and installed anew after the enrollment, since it cannot be installed over.
INSTALLED=""
if "$TMP" service status >/dev/null 2>&1; then INSTALLED=1; fi
if [ -n "$UPGRADE" ] && [ -z "$INSTALLED" ]; then
  echo "The sigilc service is not installed on this host: install sigilc with a token." >&2
  exit 1
fi

if [ -n "$INSTALLED" ]; then
  echo "Stopping service..."
  "$TMP" service stop
fi
mv -f "$TMP" "$DEST"

if [ -z "$UPGRADE" ]; then
  echo "Enrolling..."
  SIGILC_TOKEN="$TOKEN" "$DEST" enroll
  if [ -n "$INSTALLED" ]; then
    echo "Uninstalling the service of the earlier install..."
    "$DEST" service uninstall
  fi
  echo "Installing system service..."
  "$DEST" service install
fi

echo "Starting service..."
"$DEST" service start

echo "Done."
`))

// installPs1Tmpl is the Windows installer. It holds only ASCII, which reads
// the same in every encoding Windows PowerShell 5.1 may assume for it. It runs
// as a script block in the operator's own session, which exit would close, so
// every failure throws instead: a cmdlet's through $ErrorActionPreference, and
// sigilc's through its exit code, which PowerShell does not check by itself.
var installPs1Tmpl = template.Must(template.New("install.ps1").Parse(`# Sigil client installer for Windows, generated by sigils.
# Run it in an elevated Windows PowerShell 5.1 or PowerShell 7:
#   {{ .WithToken }}
param([Parameter(Mandatory = $true)][string]$Token)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $Principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw 'Run this installer in an elevated PowerShell (Run as administrator).'
}

$ServerURL = '{{ .ServerURL }}'

$MachineArch = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }
$Arch = switch ($MachineArch.ToUpperInvariant()) {
    'AMD64' { 'amd64' }
    'ARM64' { 'arm64' }
    'X86'   { '386' }
    default { throw "Unsupported Windows architecture: $MachineArch" }
}

$Dest = 'C:\Program Files\Sigil\sigilc.exe'
New-Item -ItemType Directory -Force -Path (Split-Path $Dest) | Out-Null

Write-Host "Downloading sigilc for windows/$Arch..."
Invoke-WebRequest -UseBasicParsing -Uri "$ServerURL/download/sigilc?os=windows&arch=$Arch" -OutFile $Dest

Write-Host 'Enrolling...'
& $Dest enroll --token $Token
if ($LASTEXITCODE -ne 0) { throw "sigilc enroll failed with exit code $LASTEXITCODE" }

Write-Host 'Installing system service...'
& $Dest service install
if ($LASTEXITCODE -ne 0) { throw "sigilc service install failed with exit code $LASTEXITCODE" }

Write-Host 'Starting service...'
& $Dest service start
if ($LASTEXITCODE -ne 0) { throw "sigilc service start failed with exit code $LASTEXITCODE" }

Write-Host 'Done.'
`))

// usageToken stands for the token in the usage comments of the scripts.
const usageToken = "<TOKEN>"

// installData is what the templates of the install scripts take: the base URL
// of the server, and the commands that run the script with a token, asking
// for the token, and to upgrade.
type installData struct {
	ServerURL                    string
	WithToken, AskToken, Upgrade string
}

// usages returns the data of install.sh and install.ps1.
func usages(serverURL string) (sh, ps1 installData) {
	sh.ServerURL, ps1.ServerURL = serverURL, serverURL
	sh.WithToken, ps1.WithToken = InstallCommands(serverURL, usageToken)
	sh.AskToken, ps1.AskToken = installCommands(serverURL, "", "")
	sh.Upgrade, ps1.Upgrade = installCommands(serverURL, " -s -- --upgrade", " -Upgrade")
	return sh, ps1
}

func renderInstallSh(w io.Writer, serverURL string) {
	sh, _ := usages(serverURL)
	_ = installShTmpl.Execute(w, sh)
}

// renderInstallPs1 writes the Windows installer, which is the same for every
// request: the token reaches it as the -Token argument, never through the
// server.
func renderInstallPs1(w io.Writer, serverURL string) {
	_, ps1 := usages(serverURL)
	_ = installPs1Tmpl.Execute(w, ps1)
}
