FROM golang:1.25-alpine AS builder
RUN CGO_ENABLED=0 go install github.com/letsencrypt/pebble/v2/cmd/pebble@v2.10.1 github.com/letsencrypt/pebble/v2/cmd/pebble-challtestsrv@v2.10.1

# One image serves both: run challtestsrv with --entrypoint pebble-challtestsrv.
FROM alpine:3.20
COPY --from=builder /go/bin/pebble /go/bin/pebble-challtestsrv /usr/local/bin/
ENTRYPOINT ["pebble"]
